# fly.toml app configuration file generated for netlify-rack-app on 2025-05-29T16:46:07-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'netlify-rack-app'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
